name: Sign

on:
  schedule:
    - cron: 0 14 * * *
    - cron: 0 22 * * *
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      JOB_URL: ${{$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID}}

    steps:
      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Shanghai"

      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: 'pip'
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Sign
        run: |
          python ci.py
        env:
          XYB_PASSWORD: ${{ secrets.XYB_PASSWORD }}
          XYB_PHONE: ${{ secrets.XYB_PHONE }}
          XYB_ADCODE: ${{ secrets.XYB_ADCODE }}

      - name: Notify
        uses: ZNotify/action@master
        with:
          user_id: ${{ secrets.ZNOTIFY_USER_ID }}
          content: 校友邦签到成功
          title: 校友邦
          long: "[Job Url](${{ env.JOB_URL }})"

      - name: Notify
        if: failure()
        uses: ZNotify/action@master
        with:
          user_id: ${{ secrets.ZNOTIFY_USER_ID }}
          content: 校友邦签到失败
          title: 校友邦
          long: "[Job Url](${{ env.JOB_URL }})"