name: Sign

on:
  workflow_dispatch:

  schedule:
    - 0 14 * * *
    - 0 6 * * *

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Sign
        run: |
          python ci.py
        env:
          XYB_PASSWORD: ${{ secrets.XYB_PASSWORD }}
          XYB_PHONE: ${{ secrets.XYB_PHONE }}
          XYB_ADCODE: ${{ secrets.XYB_ADCODE }}

      - name: Notify
        uses: ZNotify/action@master
        with:
          user_id: ${{ secrets.ZNOTIFY_USER_ID }}
          content: 校友邦签到成功
          title: 校友邦签到成功
          long: "[Job Url]({{$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID}})"

      - name: Notify
        if: failure()
        uses: ZNotify/action@master
        with:
          user_id: ${{ secrets.ZNOTIFY_USER_ID }}
          content: 校友邦签到失败
          title: 校友邦签到失败
          long: "[Job Url]({{$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID}})"